import './globals.css'

export const metadata = {
  title: 'Cafe Senja - Order App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body className="flex justify-center">
        <main className='w-[460px]'>
          {children}
        </main>
      </body>
    </html>
  )
}
